name: payment-reliability-lab

services:
  app:
    profiles: ["application"]
    image: payment-reliability-lab:local
    build:
      context: .
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-payment_lab}
      POSTGRES_USER: ${POSTGRES_USER:-payment_lab}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Create .env from .env.example}
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      PAYMENT_PROVIDER_BASE_URL: http://localhost:8080
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      DEPLOYMENT_ENVIRONMENT: compose
    ports:
      - "127.0.0.1:${APP_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      jaeger:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 30s

  postgres:
    image: postgres:17.11-bookworm
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-payment_lab}
      POSTGRES_USER: ${POSTGRES_USER:-payment_lab}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Create .env from .env.example}
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-55432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 30s

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.2.2
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --mode
      - dev-container
      - --smp
      - "1"
      - --default-log-level=info
    ports:
      - "127.0.0.1:${KAFKA_PORT:-19092}:19092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 15s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 30s

  jaeger:
    image: jaegertracing/jaeger:2.20.0
    ports:
      - "127.0.0.1:${JAEGER_UI_PORT:-16686}:16686"
      - "127.0.0.1:${OTLP_HTTP_PORT:-4318}:4318"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

volumes:
  postgres-data:
  redpanda-data:
